version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak-test
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-themes:/opt/keycloak/themes
    command: >
      start-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
